# -*- coding: utf-8 -*-
"""zindi004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_d0px7typaizqnrKcuFosPd1i3y_HG7D
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

import datetime

!pip install openrouteservice

import openrouteservice as ors
from openrouteservice.directions import directions

myTok = "5b3ce3597851110001cf62482bbdd980e3864e71b59568456698a112"
client = ors.Client(key=myTok)

Train = pd.read_csv("Train.csv")
Test = pd.read_csv("Test.csv")
Rider = pd.read_csv("Riders.csv")

Train = pd.merge(Train, Rider, how='left', left_on='Rider Id', right_on='Rider Id', left_index=True)
Test = pd.merge(Test, Rider, how='left', left_on='Rider Id', right_on='Rider Id', left_index=True)

# Stat descriptive

print(Train.shape)
print(Test.shape)
print(Rider.shape)

Train.describe()

set(Train.columns) - set(Test.columns)

Test.describe()



# fonction permettant de recuperer les x donnees de l'api openrouteservice puis les ajouter dans un fichier csv

def get_distance(T,var1,var2,var3,var4,file_name):
  #on cree un fichier cvs dans lequel on ajoute les infos
  with open(file_name,mode="w+",encoding="utf-8") as f:
    f.write("distance,duration\n")
    for i in T.index:
        coords=((T.at[i,var1],T.at[i,var2]),(T.at[i,var3],T.at[i,var4]))
        routes = directions(client, coords,profile='cycling-regular',language='fr')
        info = "{},{}\n"
        f.write(info.format(routes["routes"][0]["summary"]["distance"],routes["routes"][0]["summary"]["duration"]))
  return True

# exemple: pour recuperer les 2 premiers
Train_2 = Train[:2]
train_ors = get_distance(Train_2,'Pickup Long','Pickup Lat','Destination Long','Destination Lat',"2.csv")